-- Create the todos table with an auto-incrementing ID
CREATE TABLE IF NOT EXISTS todos (
  id     INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title  TEXT    NOT NULL
);

ALTER TABLE todos OWNER TO todo_user;
